import React from 'react';
import { storiesOf } from '@storybook/react';

import { ColorScheme } from '.';
import { ItemGroup } from '../../helpers/ItemGroup';
import { ItemRow } from '../../helpers/ItemRow';
import { Item } from '../../helpers/Item';

storiesOf('Color Scheme', module)
  .add('Color Scheme', () => {
    return (
      <>
        <ItemGroup
          title='Primary Colors'
        >
          <ItemRow>
            <Item>
              <ColorScheme
                text='P1'
                bgColor='#6400DC'
                borderColor='#6400DC'
                textColor='#FFFFFF'
              >
              </ColorScheme>
            </Item>
            <Item>
              <ColorScheme
                text='P2'
                bgColor='#7F7F7F'
                borderColor='#7F7F7F'
                textColor='#FFFFFF'
              >
              </ColorScheme>
            </Item>
            <Item>
              <ColorScheme
                text='Neutral White'
                bgColor='#FFFFFF'
                borderColor='#979797'
                textColor='#1D1D1D'
              >
              </ColorScheme>
            </Item>
          </ItemRow>
        </ItemGroup>
        <ItemGroup
          title='Secondary Colors'
        >
          <ItemRow>
            <Item>
              <ColorScheme
                text='S1'
                bgColor='#6400DC'
                secondaryBgColor='#8133E0'
                borderColor='#6400DC'
                textColor='#FFFFFF'
              >
              </ColorScheme>
            </Item>
          </ItemRow>
        </ItemGroup>
        <ItemGroup
          title='Alert'
        >
          <ItemRow>
            <Item>
              <ColorScheme
                text='R300'
                bgColor='#FF5252'
                borderColor='#FF5252'
                textColor='#FFFFFF'
              >
              </ColorScheme>
            </Item>
            <Item>
              <ColorScheme
                text='Y300'
                bgColor='#F7D210'
                borderColor='#F7D210'
                textColor='#FFFFFF'
              >
              </ColorScheme>
            </Item>
            <Item>
              <ColorScheme
                text='G300'
                bgColor='#32C86D'
                borderColor='#32C86D'
                textColor='#FFFFFF'
              >
              </ColorScheme>
            </Item>

          </ItemRow>
        </ItemGroup>
        <ItemGroup
          title=''
        >
          <ItemRow>
            <ItemGroup
              title='Neutral'
            >
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Neutral White'
                    bgColor='#FFFFFF'
                    borderColor='#FFFFFF'
                    textColor='#1D1D1D'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Neutral 75'
                    bgColor='#F1F1F1'
                    borderColor='#F1F1F1'
                    textColor='#1D1D1D'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Neutral 100'
                    bgColor='#E5E5E5'
                    borderColor='#E5E5E5'
                    textColor='#1D1D1D'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Neutral 200'
                    bgColor='#CCCCCC'
                    borderColor='#CCCCCC'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Neutral 500'
                    bgColor='#7F7F7F'
                    borderColor='#7F7F7F'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Neutral 800'
                    bgColor='#333333'
                    borderColor='#333333'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Neutral 900'
                    bgColor='#1D1D1D'
                    borderColor='#1D1D1D'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Neutral 1000'
                    bgColor='#000000'
                    borderColor='#000000'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
            </ItemGroup>
            <ItemGroup
              title='Red'
            >
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='R50'
                    bgColor='#FFEEEE'
                    borderColor='#FFEEEE'
                    textColor='#868687'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='R75'
                    bgColor='#FFB3B3'
                    borderColor='#FFB3B3'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='R100'
                    bgColor='#FF8585'
                    borderColor='#FF8585'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='R300'
                    bgColor='#FF5252'
                    borderColor='#FF5252'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='R400'
                    bgColor='#CC4141'
                    borderColor='#CC4141'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='R500'
                    bgColor='#8F2D2D'
                    borderColor='#8F2D2D'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
            </ItemGroup>
            <ItemGroup
              title='Green'
            >
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='G50'
                    bgColor='#EBFAF1'
                    borderColor='#EBFAF1'
                    textColor='#868687'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='G75'
                    bgColor='#A7EFC2'
                    borderColor='#A7EFC2'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='G100'
                    bgColor='#6FDE9A'
                    borderColor='#6FDE9A'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='G300'
                    bgColor='#32C86D'
                    borderColor='#32C86D'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='G400'
                    bgColor='#28A057'
                    borderColor='#28A057'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='G500'
                    bgColor='#0D7837'
                    borderColor='#0D7837'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
            </ItemGroup>
            <ItemGroup
              title='Yellow'
            >
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Y50'
                    bgColor='#FFF8D6'
                    borderColor='#FFF8D6'
                    textColor='#868687'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Y75'
                    bgColor='#FDEDA4'
                    borderColor='#FDEDA4'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Y100'
                    bgColor='#FBE277'
                    borderColor='#FBE277'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Y300'
                    bgColor='#F7D210'
                    borderColor='#F7D210'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Y400'
                    bgColor='#D5AD00'
                    borderColor='#D5AD00'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='Y500'
                    bgColor='#B99600'
                    borderColor='#B99600'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
            </ItemGroup>
            <ItemGroup
              title='Violet'
            >
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='V50'
                    bgColor='#E6D2FF'
                    borderColor='#E6D2FF'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='V75'
                    bgColor='#CDA5FF'
                    borderColor='#CDA5FF'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='V100'
                    bgColor='#A266EA'
                    borderColor='#A266EA'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='V300'
                    bgColor='#6400DC'
                    borderColor='#6400DC'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='V400'
                    bgColor='#46009A'
                    borderColor='#46009A'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
              <ItemRow>
                <Item>
                  <ColorScheme
                    text='V500'
                    bgColor='#23004D'
                    borderColor='#23004D'
                    textColor='#FFFFFF'
                  >
                  </ColorScheme>
                </Item>
              </ItemRow>
            </ItemGroup>
          </ItemRow>
        </ItemGroup>
      </>
    );
  });
