language: node_js
node_js:
  - "10.16"

install:
  - npm ci

script:
  - npm run lint
  - npm run build
  - npm run build-storybook

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script:
      - npx semantic-release
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    local_dir: docs
    target_branch: gh-pages
    on:
      branch: master
